/**
 * THE DECISION of the `balance` build step: where `\balance` goes so that the last page of a
 * two-column ACM paper ends with both columns at about the same height.
 *
 * PURE. No disk, no process. The shell in `build.ts` rebuilds the paper once per position, records
 * what it measured as an `Attempt`, and asks `nextBalanceStep` what to do next — the same split as
 * `latex-loop.ts`, so every branch of the search is a row in a table test.
 *
 * ── WHY THIS STEP EXISTS ─────────────────────────────────────────────────────
 * The publisher returned an ACCEPTED paper with "Please correct the last page balancing": the
 * bibliography filled the first column of the last page to 625 pt and the second to 304.
 *
 * ── WHY `\balance` IN THE `.bbl`, AND NOT THE CLASS OPTION OR A PACKAGE (measured, closed) ────
 * - acmart's own `balance` option calls `\balance` from `\AtEndDocument`, i.e. always from the
 *   SECOND column of the last page. balance.sty's documentation is explicit that it "must be given
 *   somewhere within the first column", and says so in the log ("You have called \balance in
 *   second column"). The option therefore does nothing.
 * - `pbalance` calls itself "experimental" and "a hack… beta quality". Measured: 450/455 once,
 *   then 625/320 after a bibliography edit. `flushend` is documented to produce defective output
 *   in some cases. Both rejected.
 * - What works, and what ACM's own production (CPC) documents as the manual fix: `\balance` inside
 *   the bibliography, in the first column of the last page. The `.bbl` is regenerated by bibtex on
 *   every build, so the insertion has to live in the build — which is this step.
 *
 * ── WHY A LINEAR SCAN, NOT A BINARY SEARCH ───────────────────────────────────
 * The outcome is not monotone in the position. Measured 2026-08-29 on the paper that prompted this:
 * position 8 balanced the page and broke the layout (an overfull box) while its neighbours did not.
 * The scan takes the FIRST position in bibliography order that passes every check.
 *
 * ── WHY THE SCAN STARTS AT THE FIRST `\bibitem`, WITH NO LOWER BOUND ─────────
 * The script this replaces started at a hand-picked 5. Measured on that paper (27 references,
 * 2026-09-24): positions 0–19 all gave the same geometry (464.2 / 461.5 pt), 20–26 the unbalanced
 * 625.2 / 303.8. The lower bound bought nothing and hid the range from the reader. What
 * does separate a good position from a bad one is not its index but where it lands on the page,
 * and two checks below read exactly that from the build instead of guessing it from a number:
 * balance.sty's own second-column warning, and the page count.
 */

import { getParser } from "@unified-latex/unified-latex-util-parse";

/**
 * Every `format` acmart accepts, in its declaration order — acmart.cls v2.03 (2024/02/04), the
 * `\define@choicekey` for `format` at the top of the class.
 */
export const ACMART_FORMATS = [
  "manuscript",
  "acmsmall",
  "acmlarge",
  "acmtog",
  "sigconf",
  "siggraph",
  "sigplan",
  "sigchi",
  "sigchi-a",
  "acmengage",
  "acmcp",
] as const;

/**
 * The formats acmart typesets in TWO columns. Read from acmart.cls v2.03, not from memory: these
 * are exactly the branches of `\@mktitle` that open `\twocolumn[…]`, and exactly the branches of
 * the `\if@ACM@balance` dispatch in `\AtEndPreamble` that load balance.sty — the class's own list
 * of formats that have a last page to balance. The rest (manuscript, acmsmall, acmlarge,
 * sigchi-a, acmcp) set the title with `\box\mktitle@bx\par` and stay one-column.
 */
export const ACMART_TWO_COLUMN_FORMATS: readonly string[] = [
  "acmtog",
  "sigconf",
  "siggraph",
  "sigplan",
  "sigchi",
  "acmengage",
];

/** acmart's default when no format is given. */
export const ACMART_DEFAULT_FORMAT = "manuscript";

/**
 * The format an acmart option list selects. Both spellings are the class's own: a bare `sigconf`
 * (`\@DeclareACMFormat`) and `format=sigconf` (the choice key). Options are applied in order, so the
 * last one wins.
 */
export function acmartFormat(options: readonly string[]): string {
  let format = ACMART_DEFAULT_FORMAT;
  for (const raw of options) {
    const [key = "", value] = raw.split("=").map((s) => s.trim());
    if (value !== undefined) {
      if (key === "format") format = value;
    } else if ((ACMART_FORMATS as readonly string[]).includes(key))
      format = key;
  }
  return format;
}

/** Whether a boolean class option is on: `review` or `review=true`, the last spelling winning. */
export function optionOn(options: readonly string[], name: string): boolean {
  let on = false;
  for (const raw of options) {
    const [key = "", value] = raw.split("=").map((s) => s.trim());
    if (key !== name) continue;
    on = value === undefined || value === "true";
  }
  return on;
}

/** What `balanceApplies` needs to know about a paper — both fields are parsed from `paper.tex`. */
export interface BalanceFacts {
  readonly documentclass: {
    readonly name: string;
    readonly options: readonly string[];
  } | null;
  /** The paper calls `\bibliography{…}` with a non-empty argument. */
  readonly bibliography: boolean;
}

/**
 * Does this paper have a last page to balance, and can rpp balance it? Every `why` is printed in
 * the plan, so a skip says what it skipped for.
 */
export function balanceApplies(facts: BalanceFacts): {
  yes: boolean;
  why: string;
} {
  const dc = facts.documentclass;
  if (!dc) return { yes: false, why: "no \\documentclass found" };
  if (dc.name !== "acmart")
    return {
      yes: false,
      why: `${dc.name} is not acmart; rpp balances acmart's two-column formats only`,
    };
  const format = acmartFormat(dc.options);
  if (!ACMART_TWO_COLUMN_FORMATS.includes(format))
    return {
      yes: false,
      why: `acmart ${format} is one-column; there is no last page to balance`,
    };
  // `review` numbers the lines, and numbered margins make both columns measure full height. The
  // publisher's balancing requirement is a camera-ready one, so there is nothing to do here.
  if (optionOn(dc.options, "review"))
    return {
      yes: false,
      why: `acmart ${format} with review numbers the lines; balancing is a camera-ready requirement`,
    };
  if (!facts.bibliography)
    return {
      yes: false,
      why: `acmart ${format} is two-column, but there is no \\bibliography — rpp places \\balance in the bibliography`,
    };
  return {
    yes: true,
    why: `acmart ${format} is two-column — will place \\balance in the bibliography`,
  };
}

// ── geometry ────────────────────────────────────────────────────────────────────────────

/** The heights of the last page's two columns, in points. */
export type Columns = readonly [left: number, right: number];

/**
 * How far apart the two columns may end, in points. It is the number every shipped ACM venue
 * profile carries as `last_page_balance_tol_pt` (the CI rule judges the same PDF with it), and the
 * harness fails the day a profile disagrees. The margin is deliberate: on the paper that was sent
 * back, the balanced build differed by 2.7 pt and the unbalanced one by 321.4 — nothing in between.
 */
export const BALANCE_TOL_PT = 120;

export const columnGap = (c: Columns): number => Math.abs(c[0] - c[1]);

export const isBalanced = (c: Columns, tol: number = BALANCE_TOL_PT): boolean =>
  columnGap(c) <= tol;

/** `left / right pt`, one decimal, the way every line of this step prints columns. */
export const formatColumns = (c: Columns): string =>
  `${c[0].toFixed(1)} / ${c[1].toFixed(1)} pt`;

/** The last page of `pdftotext -bbox` output: how many pages there are, its width, and its words. */
export interface PdfLastPage {
  readonly pages: number;
  readonly widthPt: number;
  /** The markup of the last page alone, as `columnHeights` reads it. */
  readonly xml: string;
}

/**
 * Split `pdftotext -bbox` output into pages and return the last. One call measures the page count
 * and the last page together, so no second tool (pdfinfo) is needed. The format is poppler's own
 * fixed XHTML: one `<page width=… height=…>` element per page, words inside.
 */
export function lastPdfPage(bboxXml: string): PdfLastPage | null {
  const pages = [
    ...bboxXml.matchAll(
      /<page width="([\d.]+)" height="[\d.]+">([\s\S]*?)<\/page>/g,
    ),
  ];
  const last = pages.at(-1);
  if (!last) return null;
  return { pages: pages.length, widthPt: Number(last[1]), xml: last[2] ?? "" };
}

// ── the bibliography ────────────────────────────────────────────────────────────────────

/** Depth-first, in document order: every node of a unified-latex AST. */
export function* latexNodes(node: any): Generator<any> {
  if (!node || typeof node !== "object") return;
  yield node;
  for (const child of Array.isArray(node.content) ? node.content : [])
    yield* latexNodes(child);
  for (const arg of Array.isArray(node.args) ? node.args : [])
    yield* latexNodes(arg);
}

/**
 * The offset of every `\bibitem` in a `.bbl`, in order — read by the same unified-latex parser the
 * lint rules and `parseDocumentclass` use, so a `\bibitem` in a comment is a comment. bibtex writes
 * one per entry; ACM-Reference-Format spells it `\bibitem[Label(Year)]%` + newline + `{key}`.
 */
export function bibitemOffsets(bbl: string): number[] {
  const ast = getParser().parse(bbl);
  const out: number[] = [];
  for (const n of latexNodes(ast))
    if (n.type === "macro" && n.content === "bibitem") {
      const at = n.position?.start?.offset;
      if (typeof at === "number") out.push(at);
    }
  return out;
}

/** What is inserted: balance.sty's command on a line of its own. */
export const BALANCE_LINE = "\\balance\n";

/**
 * The `.bbl` with `\balance` inserted just before the bibitem at `position` (0-based), given the
 * offsets `bibitemOffsets` found. Throws on a position that does not exist: the caller derives the
 * positions from the same offsets, so an out-of-range one is a bug here, not a paper defect.
 */
export function injectBalance(
  bbl: string,
  offsets: readonly number[],
  position: number,
): string {
  const at = offsets[position];
  if (at === undefined)
    throw new RangeError(
      `no \\bibitem #${position + 1}: the bibliography has ${offsets.length}`,
    );
  return bbl.slice(0, at) + BALANCE_LINE + bbl.slice(at);
}

/** The positions to try, in order: before each `\bibitem`, first to last. See the header. */
export function balancePositions(count: number): number[] {
  return Array.from({ length: Math.max(0, count) }, (_, i) => i);
}

// ── the search ──────────────────────────────────────────────────────────────────────────

/**
 * balance.sty's measured side effect: a balanced last page ALWAYS leaves one
 * `Overfull \vbox (1.503pt too high) … while \output is active` — the column is a point and a half
 * over its nominal height, not text running into the margin. Measured on the real paper at every
 * one of the 20 balanced positions. An overfull vbox counts as broken layout from this size up; an
 * overfull hbox (text visibly past the margin) always does.
 */
export const VBOX_TOLERANCE_PT = 3;

export interface OverfullBox {
  readonly box: "hbox" | "vbox";
  readonly pt: number;
}

export const breaksLayout = (b: OverfullBox): boolean =>
  b.box === "hbox" || b.pt >= VBOX_TOLERANCE_PT;

/** What one rebuild with `\balance` at `position` produced. */
export type Attempt =
  | {
      readonly position: number;
      readonly kind: "failed";
      /** The build error, as the compile step would show it. */
      readonly lines: readonly string[];
    }
  | {
      readonly position: number;
      readonly kind: "built";
      readonly pages: number;
      /** null — the last page has nothing to measure (a stub, or numbered lines). */
      readonly columns: Columns | null;
      /** Overfull boxes that break the layout, per `breaksLayout`. */
      readonly overfull: number;
      /** balance.sty logged that `\balance` was called in the second column. */
      readonly secondColumn: boolean;
    };

export type BuiltAttempt = Extract<Attempt, { kind: "built" }>;

/** The unbalanced build every attempt is compared with. */
export interface Baseline {
  readonly pages: number;
  readonly columns: Columns;
  readonly overfull: number;
}

/**
 * Why an attempt is not acceptable, or null when it is. The order is the order of the checks, and
 * the first failing one is the reason reported.
 *
 * - `failed`        — the rebuild did not compile.
 * - `second-column` — balance.sty says `\balance` ran in the second column: the command's own
 *                     documented misuse. On the real paper position 0 did this and still came out
 *                     balanced, by way of the page before; that is luck, not a placement.
 * - `pages`         — the page count moved. Balancing redistributes the last page and nothing
 *                     else; a different count means material moved upstream, which the last-page
 *                     measurement cannot see.
 * - `unmeasurable`  — the last page has nothing to measure.
 * - `unbalanced`    — the columns still differ by more than the tolerance.
 * - `overfull`      — more layout-breaking overfull boxes than the unbalanced build had. Compared
 *                     with the baseline, not with zero: a paper whose body already carries an
 *                     overfull hbox would otherwise fail here for a defect this step did not make.
 */
export type Rejection =
  | "failed"
  | "second-column"
  | "pages"
  | "unmeasurable"
  | "unbalanced"
  | "overfull";

export function rejection(
  a: Attempt,
  base: Baseline,
  tol: number = BALANCE_TOL_PT,
): Rejection | null {
  if (a.kind === "failed") return "failed";
  if (a.secondColumn) return "second-column";
  if (a.pages !== base.pages) return "pages";
  if (a.columns === null) return "unmeasurable";
  if (!isBalanced(a.columns, tol)) return "unbalanced";
  if (a.overfull > base.overfull) return "overfull";
  return null;
}

/** The first acceptable position in the order the attempts were made, or null. */
export function pickBalancePosition(
  attempts: readonly Attempt[],
  base: Baseline,
  tol: number = BALANCE_TOL_PT,
): number | null {
  return (
    attempts.find((a) => rejection(a, base, tol) === null)?.position ?? null
  );
}

export type BalanceStep =
  | { readonly kind: "try"; readonly position: number }
  | { readonly kind: "chosen"; readonly position: number }
  | { readonly kind: "none" };

/** Stop at the first acceptable position; otherwise try the next untried one; otherwise give up. */
export function nextBalanceStep(
  positions: readonly number[],
  attempts: readonly Attempt[],
  base: Baseline,
  tol: number = BALANCE_TOL_PT,
): BalanceStep {
  const chosen = pickBalancePosition(attempts, base, tol);
  if (chosen !== null) return { kind: "chosen", position: chosen };
  const tried = new Set(attempts.map((a) => a.position));
  const next = positions.find((p) => !tried.has(p));
  return next === undefined
    ? { kind: "none" }
    : { kind: "try", position: next };
}

/** The measured attempt whose columns came closest, whatever else rejected it. */
export function nearMiss(attempts: readonly Attempt[]): BuiltAttempt | null {
  let best: BuiltAttempt | null = null;
  for (const a of attempts) {
    if (a.kind !== "built" || a.columns === null) continue;
    if (!best?.columns || columnGap(a.columns) < columnGap(best.columns))
      best = a;
  }
  return best;
}

/** `3, 5–9, 12` — 0-based positions shown as 1-based bibitem numbers, runs collapsed. */
export function formatPositions(positions: readonly number[]): string {
  const sorted = [...positions].sort((a, b) => a - b);
  const runs: string[] = [];
  for (let i = 0; i < sorted.length;) {
    let j = i;
    while (j + 1 < sorted.length && sorted[j + 1] === (sorted[j] ?? 0) + 1) j++;
    const from = (sorted[i] ?? 0) + 1;
    const to = (sorted[j] ?? 0) + 1;
    runs.push(from === to ? `${from}` : `${from}–${to}`);
    i = j + 1;
  }
  return runs.join(", ");
}

const REJECTION_TEXT: Record<Rejection, string> = {
  failed: "did not compile",
  "second-column": "fell in the second column",
  pages: "changed the page count",
  unmeasurable: "left nothing to measure on the last page",
  unbalanced: "stayed unbalanced",
  overfull: "added an overfull box",
};

/**
 * What a failed scan tells the author: what was tried, the unbalanced baseline, the closest miss,
 * and every position grouped by why it was rejected — so the next move (edit the bibliography,
 * put `\balance` into the body text by hand) is a decision made on data.
 */
export function describeFailedScan(
  attempts: readonly Attempt[],
  base: Baseline,
  count: number,
  tol: number = BALANCE_TOL_PT,
): string[] {
  const lines = [
    `no position of \\balance balances the last page — tried ${attempts.length} of ${count} \\bibitem positions`,
    `unbalanced build: ${formatColumns(base.columns)}, tolerance ${tol} pt`,
  ];
  const near = nearMiss(attempts);
  if (near?.columns)
    lines.push(
      `closest: before \\bibitem #${near.position + 1} — ${formatColumns(near.columns)} (${REJECTION_TEXT[rejection(near, base, tol) ?? "unbalanced"]})`,
    );
  const by = new Map<Rejection, number[]>();
  for (const a of attempts) {
    const r = rejection(a, base, tol);
    if (r) by.set(r, [...(by.get(r) ?? []), a.position]);
  }
  for (const [r, ps] of by)
    lines.push(`\\bibitem #${formatPositions(ps)}: ${REJECTION_TEXT[r]}`);
  if (by.get("second-column")?.length === attempts.length)
    lines.push(
      `every position fell in the second column: the bibliography does not reach the first column of the last page, so \\balance belongs in the body text there — by hand`,
    );
  return lines;
}
